### ISSUE TITLE
[$30] Selected item under More wrong menu pointer.

### ISSUE THREAD

**Issue by vic-topcoder** [topcoder-platform/community-nav-prototype#53] opened 2019-04-15 19:54 UTC
**Describe the bug**
When the user selects an item that is collapsed under More menu, the second menu pointer is moving to a different location. Not sure if the menu content is loaded as well.

**To Reproduce**
1. Reduce the width of your browser until you have More
2. Click on More
3. Select a menu item

<img width="837" alt="Screen Shot 2019-04-15 at 12 52 37 PM" src="https://user-images.githubusercontent.com/8484061/56161136-a8db3600-5f7d-11e9-8c0d-df098b4808b2.png">

**Comment by ThomasKranitsas** [comment] 2019-04-16 16:02
Contest https://www.topcoder.com/challenges/30088636 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-04-16 16:02
Contest https://www.topcoder.com/challenges/30088636 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-04-16 16:11
Contest https://www.topcoder.com/challenges/30088636 has been updated - it has been assigned to daga_sumit.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sumitdaga** [comment] 2019-04-16 16:16
@ThomasKranitsas  @vic-topcoder 
i cannot reproduce this issue   
does this happen on a particular browser

**Comment by vic-topcoder** [comment] 2019-04-16 16:24
Safari/Mac OS

**Comment by sumitdaga** [comment] 2019-04-16 18:14
@ThomasKranitsas @vic-topcoder  
PR at #55

**Comment by ThomasKranitsas** [comment] 2019-04-17 07:38
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-04-17 07:39
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30088636<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2019-04-17 07:38 UTC
Labels: tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview
